vtex-apps/admin-pages

CHANGELOG.md
manifest.json
react/components/ComponentEditor.js

The editor wasn't saving the extension date, once the `getComponentSchema` was receiving the component name other than the component implementation.
Access: https://carousel--storecomponents.myvtex.com/carousel

Fixed save extension

---

CHANGELOG.md
react/__tests__/ComponentEditor.test.js
react/components/ComponentEditor.js

Generate the `UiSchema` from the Schema definition.
Turn the `ComponentEditor` more flexible to understand the `UiSchema` being defined by the schema 
Example of the Carousel Banner schema:
```
const bannerStructure = {
...
properties: {
...
lines: {
properties: {
numberOfLines: {
type: 'number',
widget: {
'ui:widget': 'range',
},
}
}
},
numberAleatorio: {
type: 'number',
title: 'numberAleatorio',
widget: {
'ui:widget': 'range',
},
default: 1,
minimum: 1,
maximum: 10,
},
},
}
```
Access: https://dynamic-uischema--storecomponents.myvtex.com/carousel, and play around with the carousel on edition mode, displaying the UiWdigets deep into the component schema.

Add support on ComponentEditor to Schema definition of UiSchema

---

CHANGELOG.md
react/__tests__/ComponentEditor.test.js
react/components/ComponentEditor.js

Change the implementation of singleton ComponentEditor and fix tests affected by the changes.
Access: https://singleton-editor--storecomponents.myvtex.com/shelf and check that the multiple editors don't open when clicking to edit the product summary.

Fix implementation of singleton ComponentEditor instance

---

react/__tests__/ComponentEditor.test.js
react/components/ComponentEditor.js

Remove the ComponentEditor singleton implementation.
Removing the singleton solves the bug when errors occur within the components and the editor can't recover, forcing the user to reload the page. But, it will expose the bug when opening the product summary editor inside the shelf component. That problem will be attacked in another moment.
Access: https://singleton-editor--storecomponents.myvtex.com/

Remove singleton ComponentEditor

---

CHANGELOG.md
react/EditableExtensionPoint.js
react/components/ComponentEditor.js

To add support for deep nesting object definitions in the schema used by the `ComponentEditor`.
The editor wasn't applying the correct props to the component when they were inside a nested object of the schema. Example:
```js
MyComponent.getSchema = ({ num }) => {
return {
type: 'object',
properties: {
num: { type: 'number' },
numDeep: {
type: 'object',
properties: {
...R.range(0, num).map(i => ({
[`numDeep${i}`]: { type: 'number' },
})
}
}
}
}
};
```
In the above case, when you decremented the number of properties in the editor, the `numDeepX` properties inside `numDeep` still were passed as props to the `MyComponent`.
[Visit my workspace](https://lucas--storecomponents.myvtex.com/) and decrement the number of payment forms of the `Footer` component.
You can see in [this …

Support deep hierarchies in schema

---

CHANGELOG.md
react/components/ComponentEditor.js

Add the internationalization to some properties of the `uiSchema` of the component that is embedded with the `schema`. The translated properties were `ui:help`, `ui:title`, `ui:description` and `ui:placeholder`.
This also add the possibility of using the dynamic parameter injection to the `formatMessage` function of `react-intl`, all you need to do is instead of writing a simple string with the id of the message you put an object like so
```js
const schema = {
title: { id: 'foo.bar', values: { name: 'baz' }},
}
```
This is interesting when you are creating a dynamic schema based on the `getSchema` function, and need to render something like a list and want your properties titles to be indexed.
fixes #24.
[Access this workspace](https://lucas--storecomponents.myvtex.com/) and edit the …

Internationalization of the component ui schema

---

CHANGELOG.md
manifest.json
react/PageList.js
react/components/ComponentEditor.js
react/components/EditBar.js
react/components/PageEditor.js
react/components/form/BaseInput.js
react/components/form/Dropdown.js
react/components/form/ErrorListTemplate.js
react/components/form/FieldTemplate.js
react/components/form/Radio.js
react/components/form/Toggle.js
react/editbar.global.css
react/package.json
react/yarn.lock

- Replace some of RJSF's default widgets with Styleguide components;
- Fix `ComponentEditor`'s internal z-index ;
- Restructure label logic;
- Fix `FieldTemplate`'s description logic;
- Move `ComponentEditor`'s top bar and buttons out of form;
- Make `ComponentEditor`'s close icon a button;
- Fix `BaseInput`'s `onChange` edge case bug and refactor;
- Bump RJSF;
- Create custom `ErrorListTemplate`, and move error messages and handling to widgets.
Addresses #19.
Workspace: https://alan--lojadaju.myvtex.com/.

Feature - Styleguide components

---

CHANGELOG.md
manifest.json
react/components/ComponentEditor.js
react/components/form/FieldTemplate.js
react/components/form/ObjectFieldTemplate.js
react/editbar.global.css

- Move remaining `object` field logic from `FieldTemplate` to `ObjectFieldTemplate`;
- Fix `ComponentEditor`'s top bar height @ mobile;
- Fix `ComponentEditor`'s Save & Cancel buttons height @ mobile;
- Remove description from `object` fields.
Mobile bugs.
Workspace: https://alan--lojadaju.myvtex.com/.
Before:
<hr />
After:

Fix - General fixes

---

CHANGELOG.md
react/components/form/BaseInput.js

Pass over the `min` and `max` props from the `BaseInput` to the `Input` component.
Fixes #32 
[Access this workspace](https://waza--storecomponents.myvtex.com/).

Fix maximum and minimum attributes of the range

---

CHANGELOG.md
manifest.json
react/editbar.global.css

Remove top border and spacing from `ComponentEditor`'s first object field.
Unnecessary top border and spacing in the first object field, which makes it look like there should be a field above it.
Workspace: https://alan--lojadaju.myvtex.com/.
Before:
<hr />
After:

Fix - First object field style

---

CHANGELOG.md
react/components/form/ArrayFieldTemplate.js
react/components/form/ArrayFieldTemplateItem.js

Add an accordion behavior on the fields of an array type.
Before, you could open several fields simultaneously, and it was hard to visually keep track of each individual field.
[Workspace](https://lucas--storecomponents.myvtex.com/).

Accordion behavior on array items

---

react/components/form/ArrayFieldTemplate.js
react/components/form/ArrayFieldTemplateItem.js
react/editbar.global.css

Drag handle should only be displayed when there are more than 1 item in the list, and when you click the "Add More" button the newly added item should be opened.
[Workspace](https://lucas--storecomponents.myvtex.com/).

Fix drag handle display condition and add more click behavior

---

CHANGELOG.md
react/components/ComponentEditor.tsx
react/components/form/ArrayFieldTemplateItem.js
react/editbar.global.css
react/package.json
react/yarn.lock

Add animation on the open and close of the accordion items.
The ui was a bit confusing without the animations, and made the user confused about what was going on when they add a new item, or move items.
There are a few bugs remaining, that exists on the actual library used to do the drag and drop, because it doesn't have a really good support for the children being animated.
- When a item is open, and you drag a _different_ item above the one that was open, you can't drag it past the previously opened item.
- Similarly, when you start dragging an item that was open, you can't drag past the position it was.
[Access my workspace](https://lucas--storecomponents.myvtex.com/).

Accordion items animation

---

CHANGELOG.md
manifest.json
react/components/ComponentList.tsx
react/images/PathMinus.js

The name of the attributes of the SVG icon was incorrect, so there were lots of errors appearing in the console.
https://waza2--storecomponents.myvtex.com/

Remove console errors

---

CHANGELOG.md
react/components/conditions/ConditionSection.tsx
react/components/conditions/ConditionSelector.tsx
react/typings/global.d.ts

Add `site` scope option when the component being edited is not defined only to the current page
Currently, it is not possible to select `site` scope.

Add site scope to certain components

---

CHANGELOG.md
manifest.json
react/components/form/BaseInput.js

Fix the incorrect type of the min, max and value attribute passed to the Input, because it was generating some errors in the console. 
https://waza--storecomponents.myvtex.com/

Fix the incorrect type of the min, max and value attributes passed to the Input

---

CHANGELOG.md
manifest.json
react/components/form/ArrayFieldTemplate.js
react/components/form/ArrayFieldTemplateItem.js
react/editbar.global.css

The CMS didn't support the array of array type and now it's needed.
For example, the [Footer Component](https://github.com/vtex-apps/store-components/blob/master/react/components/Footer/index.js) has a property called sectionLinks. This property has an array of sections. Each section has an array of links. The Admin Pages didn't support it properly.
[See it in my workspace](https://estacio--storecomponents.myvtex.com/admin/cms/storefront)

Added Array of Array support

---

react/components/ComponentEditor/index.tsx

- Remove `setState({ wasModified: true })` from configuration creation method;
- Enable save button on new configurations before any modifications.
Lack of a way to save configurations right after they're created.

Fix save button rendering behavior @ new configs

---

react/components/ComponentEditor/index.tsx

Replace generic check for falsy values with explicit one for `undefined`.
Currently, the user cannot delete a previously set configuration name. This PR addresses that issue.

Fix LabelEditor empty value bug

---

.gitignore
CHANGELOG.md
manifest.json
react/components/ComponentEditor/index.tsx

Deep uiSchema now gets array items.
It wasn't possible to set widgets inside array items.
[Access the workspace](https://estacio--storecomponents.myvtex.com/admin/cms/storefront)

Deep uiSchema now gets array items.

---

CHANGELOG.md
manifest.json
react/components/Admin/Redirects/RedirectForm/Form.tsx
react/components/Admin/Redirects/RedirectForm/typings.d.ts
react/components/Admin/Redirects/RedirectForm/utils.ts
react/components/Admin/Redirects/RedirectList/index.tsx
react/components/Admin/Redirects/RedirectList/typings.d.ts
react/components/Admin/Redirects/typings.d.ts
react/locales/en.json
react/locales/es.json
react/locales/pt.json

- Fix Apollo cache/fetch logic;
- Remove loading from remove button outside of modal;
- Add periods to empty state i18n texts;
- Remove some `console.log`s.
Post-mutation cache issues.
Workspace: https://alan--lojadaju.myvtex.com/admin/cms/redirects.

Fix - Redirect list cache

---

CHANGELOG.md
manifest.json
react/editbar.global.css

It fixes a small bug caused by tablet positioning on storefront.
When the page height was too low to fit the device, the parts exceding the height were hidden. Now, I'm limiting the height of the device so that it can always be shown fully.
Workspace with change applied: https://adminpages93--storecomponents.myvtex.com/admin/cms/storefront
Access the storefront editor and switch to a device display that doesn't fit your browser window.
Before:
After:

Fix mobile/tablet positioning on storefront

---

CHANGELOG.md
manifest.json
react/components/EditorContainer.tsx

- Replace a few `EditorContainer` styles — mainly `calc--width`s;
- Remove some animations (for now);
- Format previous code.
Non-responsive behavior when admin sidebar gets expanded/collapsed.
Workspace: https://alan--lojadaju.myvtex.com/admin/cms/storefront.
<hr />

Fix - EditorContainer responsiveness

---

CHANGELOG.md
manifest.json
react/components/ComponentsList.tsx

Sort components from `ComponentsList` by display order (top/left first).
Unintuitive component order.
Workspace: https://alan--lojadaju.myvtex.com/admin/cms/storefront/.
<hr />

Feature - Ordered component list

---

CHANGELOG.md
manifest.json
react/editbar.global.css

Add `calc--width` CSS class.
Missing CSS class declaration (used [here](https://github.com/vtex-apps/admin-pages/blob/5fd0028829759f28b1f6448dbb2b25508bbcb0f8/react/components/EditorContainer.tsx#L179)).

Fix - Missing calc--width

---

CHANGELOG.md
manifest.json
react/EditorProvider.tsx
react/typings/global.d.ts

- Fix i18n messages update logic;
- Add `__getEmitter` method to `Window` (if `canUseDOM`);
- Add custom methods to `Window` interface;
- Fix `EditorProvider`'s typing and formatting, and improve its readability.
I18n issues.
Workspace: https://fixruntimecustommessages--lojadaju.myvtex.com/admin/cms/storefront.

Fix - Runtime custom messages

---

CHANGELOG.md
manifest.json
pages/pages.json
react/components/EditorContainer.tsx

This PR disable `ssr` for the `HighlightOverlay` extension.
Server side rendering was pushing unwanted CSS to production apps.

Disable SSR for HighlightOverlay

---

CHANGELOG.md
manifest.json
react/EditorProvider.tsx
react/PageEditor.tsx
react/components/MessagesContext.tsx

Add MessagesContext and passing iframeMessages to `PageEditor` file.
It fixes component titles on storefront.
Workspace: https://fixcomponentnames--storecomponents.myvtex.com/
1. Enter on [admin home](https://fixcomponentnames--storecomponents.myvtex.com/admin) 
2. Navigate to Storefront

Fix components messages

---

CHANGELOG.md
manifest.json
react/components/ComponentEditor/index.tsx
react/components/ConditionsSelector/ScopeSelector.tsx
react/components/ConditionsSelector/index.tsx

ScopeSelector Dropdown was replaced by Styleguide's Dropdown component but the API wasn't updated. This PR updates the change handler.
Fix Scope Selector behaviour so user can select scope.

Fix ScopeSelector behaviour

---

CHANGELOG.md
manifest.json
pages/pages.json
react/locales/en.json
react/locales/es.json
react/locales/pt.json

- Move admin links to CMS section;
- Rename "page list" to "pages".
The Pages' links should be under the CMS section.
Workspace: https://featuremovemenulinks--storecomponents.myvtex.com/admin.
- Redesign (non-breaking change that improves current functionality)

Feature - Move menu links

---

CHANGELOG.md
react/components/ComponentsList/getComponents.test.ts
react/components/ComponentsList/getComponents.ts
react/components/ComponentsList/index.tsx
react/typings/render.d.ts
react/utils/components.ts

Implement new logic for components being rendered using `props.elements` from the extension.
Previsible components list order.

New get components logic

---

CHANGELOG.md
manifest.json
react/HighlightOverlay.tsx

`HighlightOverlay` now queries for more than one DOM element for a given `data-extension-point` attribute, and then returns the first non-empty one – i.e., whose both width and height are greater than zero.
Uncovered edge case where a component has two or more DOM elements that alternate visibility based on the user device.
Workspace: https://fixhighlightoverlay--storecomponents.myvtex.com/admin/cms/storefront.
---
- Bug fix (a non-breaking change which fixes an issue).

Fix - Highlight overlay

---

manifest.json
pages/blocks.json
pages/interfaces.json
pages/plugins.json

Merge `HighlightOverlay` fixes and inject navigation data on admin by using plugins. 
Storefront v3 milestone.
Important: this shouldn't be working yet as some other necessary PRs weren't merged, but they shouldn't break anything either.

Highlight overlay and inject menu items on admin

---

react/components/EditorContainer/Sidebar/ConfigurationList/index.tsx

Change default configuration scope to `specific`.
Wrong default configuration scope.
Workspace: https://fixdefaultconfigurationscope--storecomponents.myvtexdev.com/admin/cms/storefront.

Change default configuration scope to "specific"

---

messages/en.json
messages/es.json
messages/pt.json

Fix editing path label i18n.
Outdated i18n texts and lowercase "URL".
Workspace: https://fixeditingpathi18n--storecomponents.myvtexdev.com/admin/cms/storefront.

Fix editing path label i18n

---

CHANGELOG.md
react/components/EditorContainer/IframeNavigationController.tsx

Fix bug that navigation wasn't removing listeners.
`window.confirm` always showing when there was any change.

Remove listeners on navigation.

---

react/components/EditorContainer/Sidebar/ComponentList/index.tsx
react/components/EditorContainer/Sidebar/Content.tsx
react/components/EditorProvider.tsx
react/typings/global.d.ts

Reset component list/configurations selector and add is loading when navigating.
User may be editing the wrong component.

Unset editTreePath and add loading state

---

react/components/EditorContainer/Sidebar/Content.tsx
react/components/EditorProvider.tsx
react/typings/global.d.ts

Make loading more consistent when navigating.
When navigating to same path, the sidebar entered its loading state and would get stuck in it because the "stop loading" condition is a change in route.
[ch7233]

Fix loading in same path navigation

---

react/components/EditorContainer/Sidebar/ConfigurationList/index.tsx
react/utils/blocks/index.ts

Adapt `saveContent` mutation's `treePath` parameter formation logic.
The `saveContent` mutation's `treePath` parameter formation logic has been changed and, therefore, the code must be updated.
Workspace: https://featureadaptcontentsaving--storecomponents.myvtexdev.com/admin/cms/storefront.

Adapt saveContent mutation's treePath parameter formation logic

---

react/PageEditor.tsx
react/components/EditorContainer/StoreIframe.tsx

Users couldn't navigate using `admin/cms/storefront/<targetPath>`.
[ch7564]

Address bar navigation

---

CHANGELOG.md
manifest.json
messages/context.json
package.json

As the title says.
There was no `pages.editor.store.button.settings.title` id in `context.json` file.
[Access the workspace](https://pwa--storecomponents.myvtex.com/admin/cms/storefront)
Before
After

Fix store setting button intl

---

CHANGELOG.md
manifest.json
react/components/DomainMessages.ts
react/components/EditorProvider.tsx
react/queries/MessagesForDomain.graphql
react/typings/global.d.ts

Before setting messages, we should query pages-graphql asking for the messages of the correct domain and components for generating the store editor

Makes messages query before setting messages

---

CHANGELOG.md
manifest.json
package.json
react/components/EditorContainer/Sidebar/ConfigurationList/index.tsx
react/components/EditorContainer/graphql/SaveContent.graphql
react/components/EditorContainer/mutations/SaveContent.tsx

Always save content for the current block instead of getting the best one available (for `header`, `footer` and other blocks that are saved for multiple templates).
[https://fixsavecontent--storecomponents.myvtex.com/admin/cms/storefront](https://fixsavecontent--storecomponents.myvtex.com/admin/cms/storefront)

Passing blockId to SaveContent mutation.

---

CHANGELOG.md
manifest.json
package.json
react/components/EditorContainer/StoreEditor/Store/index.tsx

As the title says.
Improving UX with this sticky tabs. Better when switching contexts.
[Access the workspace](https://pwa--storecomponents.myvtex.com/admin/cms/storefront) and see it working in the Store Settings menu.

Add sticky property to tabs at Store Settings menu

---

CHANGELOG.md
manifest.json
react/components/EditorContainer/Sidebar/Content.tsx

`useMemo` on `getIniitalComponents`.
It was being recalculated every render.

Fix performance by using useMemo on Content.

---

CHANGELOG.md
manifest.json
pages/interfaces.json

Make highlight-overlay lazy to not be loaded on store
`vtex.admin-pages` assets are being loaded on store
Before:
After (linked workspace):

Make highlight-overlay lazy to not be loaded on store

---

CHANGELOG.md
manifest.json
react/components/EditorContainer/IframeNavigationController.tsx
react/components/EditorContainer/Sidebar/ComponentEditor/index.tsx
react/components/EditorContainer/Sidebar/ConfigurationList/ContentEditor/index.tsx
react/components/EditorContainer/Sidebar/ConfigurationList/LayoutEditor/index.tsx
react/components/EditorContainer/Sidebar/ConfigurationList/index.tsx
react/components/EditorContainer/Sidebar/FormMetaContext.tsx
react/components/EditorContainer/Sidebar/index.tsx
react/components/EditorContainer/Sidebar/typings.d.ts
react/components/EditorProvider.tsx
react/components/form/BaseInput.tsx
react/components/form/Dropdown.tsx
react/components/form/IOMessage.tsx
react/components/form/TextArea.tsx
react/components/form/Toggle.tsx
react/components/form/typings.d.ts
react/package.json
react/typings/global.d.ts
react/utils/components/index.ts
react/utils/components/typings.d.ts
react/yarn.lock

- When deleting a configuration, keep the loader until the configuration has been deleted;
- Bug fix: inconsistent content edition caused by desynchronized Runtimes;
- Bug fix: configuration list not being updated after creating/deleting configurations.
Mainly content edition issues.
Workspace: https://i18n--storecomponents.myvtex.com/admin/cms/storefront.
- Bug fix (a non-breaking change which fixes an issue).
- https://github.com/vtex-apps/render-runtime/pull/296.

Fix - Configuration list behavior

---

CHANGELOG.md
manifest.json
react/components/EditorContainer/Sidebar/ComponentList/SortableList/SortableListItem/Item.tsx
react/components/EditorContainer/Sidebar/utils.ts
react/typings/global.d.ts
react/utils/components/index.ts

Allow user to put the `title` key in their `blocks.json`.
Storefront with user defined names for better organizarion.
[Workspace](https://blockswithnames--storecomponents.myvtexdev.com/admin/cms/storefront)
| Project        | PR                     |
| ------------- |:-------------:|
| `builder-hub` | [https://github.com/vtex/builder-hub/pull/566](https://github.com/vtex/builder-hub/pull/566) |
| `pages-graphql`      |  [https://github.com/vtex/pages-graphql/pull/206](https://github.com/vtex/pages-graphql/pull/206)   |

Blocks have names too

---

CHANGELOG.md
manifest.json
messages/context.json
messages/en.json
messages/es.json
messages/pt.json
package.json
react/components/EditorContainer/Sidebar/ConfigurationList/ContentEditor/ConditionControls/ScopeSelector/index.tsx
react/components/EditorContainer/Sidebar/ConfigurationList/ContentEditor/ConditionControls/index.tsx
react/components/EditorContainer/Sidebar/ConfigurationList/List/Card/index.tsx
react/components/EditorContainer/Sidebar/ConfigurationList/List/Card/typings.d.ts
react/components/EditorContainer/Sidebar/ConfigurationList/List/Card/utils.ts
react/components/EditorContainer/Sidebar/ConfigurationList/index.tsx
react/components/EditorContainer/Sidebar/ConfigurationList/utils.ts

- When the page context can't be identified, set the configuration scope as "this template" and display a toast with a brief explanation;
- Fix the page context evaluation logic in configuration cards' tags.
Issues with unidentified page contexts.
Workspace: https://fixunidentifiedpagecontexts--storecomponents.myvtex.com/admin/cms/storefront/thisbranddoesnotexist/b.

Fix - Unidentified page contexts

---

CHANGELOG.md
manifest.json
messages/en.json
messages/es.json
messages/pt.json
react/components/EditorContainer/Sidebar/index.tsx
react/components/EditorContainer/StoreEditor/Styles/index.tsx
react/components/EditorContainer/StoreEditor/index.tsx
react/components/EditorContainer/Topbar/index.tsx
react/components/EditorContainer/index.tsx
react/components/EditorProvider.tsx

To persist editor state when previewing website.
Editor losing state when previewing website.
Change state on any storefront editor (e.g. content or styles).
Click on the little eye on the draggable widget inside the store iframe.
Watch the editor vanish.
Click on the little pencil which replaced the little eye on the draggable widget inside the store iframe.
Watch the editor raise from the ashes with same state.
All this can be done on https://fixhideeditor--storecomponents.myvtexdev.com/admin/cms/storefront

Fix: Keep editor state when previewing website

---

CHANGELOG.md
manifest.json
react/components/EditorContainer/StoreEditor/Styles/index.tsx

To insert style editor tags right after original tachyons tag.
Avoid custom styles preview overriding other styles (e.g. component css overrides).
You can test the fix on:
- https://fix--storecomponents.myvtexdev.com/admin/cms/storefront
And reproduce the bug on:
- https://bug--storecomponents.myvtexdev.com/admin/cms/storefront
To do it just open the styles editor and try to edit the first (and selected) style.
On `bug` workspace style of the header will change, on `fix` it will remain the same.

Insert style editor tags right after original tachyons tag

---

CHANGELOG.md
manifest.json
package.json
react/components/EditorContainer/Sidebar/ComponentEditor/ConditionControls/Scheduler.tsx

Fix `Scheduler`'s second `DatePicker`'s (`to`) position.
Workspaces:
- Before: [https://instore.myvtex.com/admin/cms/storefront](https://instore.myvtex.com/admin/cms/storefront);
- After: [https://vtexdaycms--instore.myvtex.com/admin/cms/storefront](https://vtexdaycms--instore.myvtex.com/admin/cms/storefront).
Before:
<hr>
After:

Fix Scheduler's 'to' DatePicker's position

---

CHANGELOG.md
react/components/form/ArrayFieldTemplateItem.tsx

The trash icon button was being triggered when pressing enter because
any `<button>` inside a `form` is interpreted as `type="submit"` by
default. This sets it to `type="button"`, which is not triggered when
submitting the form.
Pressing enter was deleting the content
https://nardi--storecomponents.myvtex.com/admin/cms/storefront
Edit a carousel item, click inside a field and press enter. It should
not be deleted — only saved.

Fix: deleting content on enter

---

CHANGELOG.md
manifest.json
react/components/EditorContainer/StoreEditor/Store/PWAForm/components/withPWASettings.tsx

As the title says.
It was missing the fact that when the icons are set before the manifest, the manifest is not empty but the colors are not set.

Fix withPWASettings condition to query the default colors

---

CHANGELOG.md
manifest.json
react/components/admin/pages/Form/index.tsx
react/components/admin/pages/Form/utils.test.ts
react/components/admin/pages/Form/utils.ts

Fix bug when creating route.
When having nested paths (e.g., `/about/us`), we were creating a routeId with `/` (`about/us`), and this was causing some issues, because the `/` is a special character.

Fix routeId generation

---

CHANGELOG.md
manifest.json
package.json
react/components/EditorContainer/Sidebar/ConfigurationList/index.tsx

When deleting a content configuration, the configuration list's `activeExtension` wasn't being updated and `updateRuntime` wasn't being run synchronously.
1. Choose any block from the sidebar and click it;
2. Create a new configuration and save it;
3. Delete the configuration you've just created;
4. Open another configuration and close it **without making changes**;
5. Notice that the iframe's Runtime is restored to its current default state (the one that was active before step 4).
Workspace: https://fixconfigdeletionactiveextension--storecomponents.myvtex.com/admin/cms/storefront.

Fix: update and clean-up steps after configuration deletion

---

CHANGELOG.md
messages/en.json
messages/es.json
messages/pt.json
react/components/EditorContainer/Topbar/index.tsx
react/components/EditorContainer/index.tsx
react/editbar.global.css

Several users are editing content in development workspace and are ending up
loosing that work because development workspace cannot be promoted to
production.
This PR adds a warning when in development mode so users will be able to
differentiate both environments.
[Workspace](https://nardi--storecomponents.myvtex.com/admin/cms/storefront/)
When entering in the storefront in development mode (link above) you
will see a yellow warning telling you not add real changes.
- Breaking change (fix or feature that would cause existing functionality to change)
- Technical improvements (chores, refactors and overall reduction of technical debt)

Warn user when editing in development workspace

---

CHANGELOG.md
manifest.json
messages/context.json
messages/en.json
messages/es.json
messages/pt.json
react/components/EditorContainer/index.tsx

Alerts user that his changes in master will reflect the live store.
To test this, I'd have to launch a beta version and install it in master. Since it's a simple change, I don't think it's necessary.

Alert when in master workspace

---

CHANGELOG.md
react/utils/components/index.ts

Save content wasn't sending the proper strings.
[Workspace](https://test--instore.myvtex.com/admin/cms/storefront)
---|---
✔️| Bug fix 
_ | Technical improvements 
🦋 effect
[ch14338]

Fix content save

---

CHANGELOG.md
react/components/EditorContainer/Sidebar/ConfigurationList/index.tsx
react/utils/components/index.ts

Fix error when saving empty form for objects
Save a new content with an empty collection for a shelf at
https://jey--instore.myvtex.com/admin/cms/storefront
- [] Updated `CHANGELOG.md`.
---|---
_ | Bug fix 

Empty fields add empty field by type

---

CHANGELOG.md
react/utils/components/index.ts

i18n mapping is stopped when data is invalid
i18n mapping and data validation are different things, this way we do continue to map i18n content even when data is invalid.
---|---
_ | Bug fix 

Add allErrors flag to ajv validation

---

CHANGELOG.md
react/utils/components/index.ts

Displaying i18n mapping hash id when saving RichText content
Edit any RichText content on
https://jey--alssports.myvtex.com/admin/cms/storefront
---|---
_ | Bug fix 

Add all IOMessage formats to i18nMapping

---

CHANGELOG.md
react/components/EditorContainer/index.tsx

Fix editor height when master workspace alert is active.
[Workspace](https://fixeditorheight--storecomponents.myvtex.com/admin/cms/storefront)
Before:
After:
---|---
✔️ | Bug fix 

Fix editor height

---

CHANGELOG.md
react/__mocks__/vtex.render-runtime.ts
react/components/EditorContainer/Sidebar/ComponentEditor/utils.test.ts
react/components/EditorContainer/Sidebar/ComponentEditor/utils.ts
react/package.json
react/typings/global.d.ts
react/typings/json-schema-traverse.d.ts

We were ignoring uiSchema definitions from JSONSchema dependencies
At https://jey3--storecomponents.myvtex.com/admin/cms/storefront
Edit the Carousel, add a new banner and select image-text as content-type, images widget should be the image-uploader widget.
---|---
_ | Bug fix 
_ | Technical improvements 
`User Notes`: Components with dynamic form were not displaying custom widgets.
**Previous:**
**Current:**

Add support to uiSchema from JSONSchema dependencies

---

CHANGELOG.md
react/components/EditorContainer/index.tsx

Flex behavior on smaller viewports.
[Workspace](https://sidebarbreakpoint--storecomponents.myvtex.com/admin/cms/storefront)
Before:
After:

Sidebar breakpoint

---

CHANGELOG.md
react/components/admin/pages/Form/Form.tsx
react/components/admin/pages/Form/index.tsx
react/components/admin/pages/Form/typings.d.ts
react/components/admin/pages/Form/utils.ts
react/components/admin/pages/utils.ts
react/package.json
react/yarn.lock

Enable editing title of pages that have *no* context attached, so users can define its own relevant SEO title.
[Workspace](https://partialroute--instore.myvtex.com/admin/cms/pages)

Partial route save and title in "standard" pages

---

CHANGELOG.md
react/components/EditorContainer/Sidebar/ConfigurationList/index.tsx
react/components/EditorContainer/Sidebar/Content.tsx

Fix the usage of wrong tree paths in sitewide blocks.
[Workspace](https://fixsitewideblockstreepath--storecomponents.myvtex.com/admin/cms/storefront)
1. Header => Notification bar;
2. Footer => Menu => News;
3. Any sitewide block :)
N/A.

Fix the usage of wrong tree paths in sitewide blocks

---

CHANGELOG.md
react/components/EditorContainer/Sidebar/ComponentEditor/hooks.ts

The component form state stack's `pop` was treating the popped state as the new active one. However, the active state should always be the one at the top of the stack.
[Workspace](https://fixbannerediting--storecomponents.myvtex.com/admin/cms/storefront)
Open and close a Carousel configuration.

Fix component form state stack handling logic

---

CHANGELOG.md
messages/en.json
messages/es.json
messages/pt.json
react/components/EditorContainer/StoreEditor/Store/PWAForm/index.tsx

Fixes splash screen preview `src` and add **preview** in the title.
[Workspace](https://thay--storecomponents.myvtex.com/admin/cms/site-editor/)
Open store settings and go to advanced.
**Before**:
**After**:

Fix splash screen preview and change title in form

---

CHANGELOG.md
react/HighlightOverlay.tsx
react/typings/global.d.ts

HighlightOverlay makes the iframe height bigger when hovering over a component that isn't in the DOM.
[Workspace](https://fixhover--storecomponents.myvtex.com/admin/app/cms/site-editor)

Fix: highlight overlay

---

CHANGELOG.md
react/components/EditorContainer/Sidebar/ComponentEditor/index.tsx
react/components/EditorContainer/Sidebar/ConfigurationList/index.tsx
react/components/EditorContainer/Sidebar/FormMetaContext.tsx
react/components/EditorContainer/Sidebar/typings.d.ts
react/components/form/BaseInput.tsx
react/components/form/I18nInput.tsx
react/components/form/TextArea.tsx
react/components/form/typings.d.ts
react/package.json
react/utils/components/index.ts
react/utils/components/typings.d.ts
react/yarn.lock

When editing i18n fields, there are a few scenarios in which the i18n key itself is being saved/displayed; this PR addresses that issue.
[Workspace](https://fixi18nsaving--alssports.myvtex.com/admin/app/cms/site-editor/)
Edit any block with i18n fields, e.g. "Rich Text".
While there isn't currently an efficient way to update the inner Runtime's intl, this solution uses the `IOMessage`'s fallback behavior to modify i18n properties. Since the …

Replace i18n editing logic to not use addMessages

---

CHANGELOG.md
react/components/EditorContainer/Sidebar/ConfigurationList/index.tsx
react/components/form/BaseInput.tsx
react/components/form/I18nInput/index.tsx
react/components/form/I18nInput/utils.ts
react/components/form/TextArea.tsx
react/components/form/typings.d.ts

The PR #279 used the second argument of the `onChange` function to pass the event target to `I18nInput`, but it turns out that RJSF's default `onChange` handles its second argument in a different way, so non-i18n text inputs ended up throwing some errors; this PR addresses that issue.
[Workspace 1](https://fixi18nsaving--alssports.myvtex.com/admin/app/cms/site-editor/)
[Workspace 2](https://fixi18nsaving--exitocol.myvtex.com/admin/app/cms/site-editor)
Edit any text input field.
| \_  | Breaking …

Fix widgets' onChange and recent i18n changes

---

CHANGELOG.md
messages/context.json
messages/en.json
messages/es.json
messages/pt.json
react/components/DomainMessages/editorMessagesFromRuntime.ts
react/components/DomainMessages/index.tsx
react/components/DomainMessages/typings.d.ts
react/components/EditorContainer/IframeNavigationController.tsx
react/components/EditorProvider.tsx

Every time there's a change, the `__provideRuntime` function calls the `messages` service, even when there are no changes in the components. This is extremely inefficient since the request takes ~2s on a fast internet and on the smallest store (`storecomponents`).
So to improve the responsiveness, this PR adds a local cache that returns the messages and avoids making the request if possible.
**Bonus change:** Add localized messages for confirm prompt that opens when you try to navigate while form is open.
[Workspace](https://messageslocalcache--storecomponents.myvtex.com/admin/cms/site-editor/)
Doing:
1. Open configuration
2. Type something and wait for change on iframe
3. Type something and wait for change on iframe
Before:
After: …

Domain messages local cache

---

CHANGELOG.md
messages/context.json
messages/en.json
messages/es.json
messages/pt.json
react/components/EditorContainer/Sidebar/Content.tsx

Eternal loading when the ListContent query fails.
Both of the workspace below contain the new code, but there's an error being thrown on purpose in the first one.
To check the error handling: [workspace](https://fixcontenteternalloadingwitherror--storecomponents.myvtex.com/admin/app/cms/site-editor).
To make sure everything else still works: [workspace](https://fixcontenteternalloading--storecomponents.myvtex.com/admin/app/cms/site-editor).
N/A.
| \_  | Technical …

Add error handling to ListContent query

---

CHANGELOG.md
react/components/HighlightOverlay/hooks/useHighlightedElementInfo.ts
react/components/HighlightOverlay/index.tsx

1. When you click to edit a block that isn't rendered, the Highlight appears in the last valid block, for example, when you hover over the `RIch Text` and click to edit the `Footer`, this is what happens:
The Highlight appears on the `Rich Text` instead of disappearing.
2. Hovering over a block that is rendered as a list (e.g., `Product Summary` inside `Shelf`), the current criteria selects the first element that is in the screen, however it doesn't necessarily mean that it is **visible**. In the shelf's case, its container has a width with `overflow: hidden` that hides the first `Product Summary` in big resolutions:
[Workspace](https://fixhighlight--storecomponents.myvtex.com/admin/app/cms/site-editor) …

Fix highlight bugs

---

CHANGELOG.md
react/components/EditorContainer/Sidebar/Transitions/Enter/index.tsx
react/components/EditorContainer/Sidebar/Transitions/Enter/styles.css

Users couldn't schedule content because datepicker was not visible in
the sidebar.
[Workspace](https://fixmodal--storecomponents.myvtex.com/admin/app/cms/site-editor)
The reason why I removed the transform property is because z-index does
not play well with it. Thus, in order to make z-index work, we have to
rely on the element not having a transform property.

Fix: users not able to schedule content

---

CHANGELOG.md
react/PageEditor.tsx

Race condition that makes editor keys load with i18n strings
[Workspace](https://gimenesrc--storecomponents.myvtex.com/admin/app/cms/site-editor)

Attemp to fix race condition in editor messages

---

CHANGELOG.md
messages/context.json
messages/en.json
messages/es.json
messages/pt.json
react/components/EditorContainer/StoreEditor/Store/PWAForm/utils/constants.ts

Now it's possible to show ` 'add to home screen'` prompt from order placed.
[Workspace](https://thay--storecomponents.myvtex.com/checkout/orderPlaced/?og=949500478939)
|  ✔️  | New feature                        |

Add checkout option in promptOnCustomEvent

---

CHANGELOG.md
react/components/PageForm.tsx

When editing an existing page, the available templates' IDs hold the complete version of the origin app, while the page's template uses the `<major>.x` format. Therefore, the active template will never match any of the available ones; this PR addresses that issue.
[Workspace](https://phdro--madesa.myvtex.com/admin/cms/pages)
Open existing pages and make sure that the corresponding template appears as the default value for the selector.
N/A.

Fix page form schema's default template selection

---

CHANGELOG.md
react/components/EditorContainer/EditableText/index.tsx
react/components/EditorContainer/EditableText/styles.css
react/components/EditorContainer/Sidebar/BlockEditor/BlockConfigurationEditor/index.tsx
react/editbar.global.css

There was low visibility that the text that goes below the Editor Header
was editable.
We've now updated it style to allow users to understand better that they
can and should update the content title.
[Workspace](https://ch25535--storecomponents.myvtex.com/admin/app/cms/site-editor)
Edit a block and fidget with renaming its content
| ✔️ | New feature                        |

Update block editor title input

---

CHANGELOG.md
admin/navigation.json

Add `styles` menu item into GoCommerce sidebar.
https://gustavo--gcqa.mygocommerce.com/admin/cms/styles
| x | New feature                        |

Add styles menu item to GoCommerce sidebar too

---

CHANGELOG.md
react/components/EditorContainer/Sidebar/index.tsx
react/components/EditorContainer/index.tsx

There is a significant layout instability when loading the site editor
that causes the site to be abruptly resized
Load the site editor in the link below and verify that there is no
layout instability anymore.
[Workspace](https://nardi--storecomponents.myvtex.com/admin/app/cms/site-editor)
|  ✔️   | Bug fix                                |

Fix layout instability when loading site editor

---

CHANGELOG.md
react/components/EditorContainer/Topbar/ContextSelectors/LocaleSelector.tsx

Changing to a binding with a default locale different than the current one wouldn't update the locale selector's value.
[Workspace](https://fixlocaleselectorstate--btglobal.myvtex.com/admin/app/cms/site-editor)
N/A.
N/A.

Fix - Locale selector state

---

CHANGELOG.md
react/components/EditorContainer/index.tsx

The styles admin was displaying a loading in the right side. This loading
animation was removed since there was nothing to be displayed there.
Check that the loading does not appear in the right
[Workspace](https://nardi3--storecomponents.myvtex.com/admin/cms/styles)

Fix: incorrect loading in styles

---

CHANGELOG.md
manifest.json
react/InstitutionalPageForm.tsx
react/PageForm.tsx
react/components/admin/pages/Form/index.tsx
react/queries/DeleteRoute.graphql
react/typings/global.d.ts

User routes will be supported by render as rewriter internal routes.
This PR enables pages to store this routes in rewriter when the dataSource: 'vtex.rewriter' is given.
When dataSource is not provided we still save the routes in colossus, this decision was made to keep backwards compatibility for tenants that don't have rewriter.
[Should be merged after this PR pages-graphql #360](https://github.com/vtex/pages-graphql/pull/360)
https://jey--storecomponents.myvtex.com/admin/cms/pages
1 - Add any landing page.
2 - Access it, it should work.
3.- Delete the new page added.
If you want to check the route in rewriter, there's a graphql query below
- Just go to: https://jey--storecomponents.myvtex.com/admin/graphql-ide, select vtex.rewriter and then place the query below:
```query internal{ …
```

Save user routes as rewriter internal routes

---

CHANGELOG.md
react/PageEditor.tsx
react/components/EditorContainer/Topbar/UrlInput.tsx
react/components/EditorProvider.tsx

Some pages will return 404 without querystring. Trying to edit those page won't work because Site Editor is not taking into account querystrings in the URL.
Make sure you see products when entering this workspace:
[Workspace](https://nardi--hushpuppiescl.myvtex.com/admin/cms/site-editor/289?map=productClusterIds)
While in production you won't be able to:
[Production](https://hushpuppiescl.myvtex.com/admin/cms/site-editor/289?map=productClusterIds)

Take querystring into account when loading iframe

---

CHANGELOG.md
react/PageEditor.tsx

Since latest relase (that wasn't deployed to all stores), when enterign in the home of a store, it would append `undefined` to it. This PR fixes that.
You should be able to use Site Editor normally 
[Workspace](https://pathundefined--miriadeit.myvtex.com/admin/app/cms/site-editor)

Fix: undefined in the url path

---

react/components/admin/pages/Form/index.tsx

Pages with only one or two template variations for some reason were mutating
incorrectly. The property `pages` was supposed to be an array of Pages, but the
it looks like the `diff`  function is turning it into an object at runtime, and
thus Typescript cannot prevent it from happening.
Try adding a conditional template to Home here and it should work:
[Workspace](https://nardi--aldi.myvtex.com/admin/app/cms/pages)
https://www.loom.com/share/ee5e109293754e829623dbce49e28182 …

Fix: Some pages wouldnt allow conditional template

---

CHANGELOG.md
react/RedirectList.tsx
react/components/admin/redirects/consts.ts
react/queries/Redirects.graphql
react/typings/global.d.ts

Users want to see the spreadsheet with the binding field to know to what binding that redirect belongs to.
https://fidelis--powerplanet.myvtex.com/admin/cms/redirects/
click on exportar and check the result.

add binding field to redirects spreadsheet

---

CHANGELOG.md
react/RedirectForm.tsx

Currently the redirect form component is not taking into account the redirect query string when querying rewriter. This PR fixes that
You can create a redirect with query strings in the `FROM` path, when trying to edit the redirect the form will not render.
Test workspace:
https://fox2--fashion2.myvtex.com/admin/cms/redirects/a/?v=12

Uses querystring to query redirect

---

CHANGELOG.md
react/components/EditorContainer/StoreIframe.tsx
react/components/admin/pages/Form/SelectConditions.tsx
react/components/form/ImageUploader/Dropzone.tsx
react/utils/components/index.ts

The time that a template went online was not consistent. With this update, the time a page with be scheduled will be midnight of the day selected. And the time will be based on the user's timezone.

Force template date to be midnight

---

CHANGELOG.md
react/components/EditorContainer/StoreIframe.tsx

The `render-server` does not know where the page is being rendered, the iframe flag will help to identify it.
Some site editor blocks sometimes disappear because of performance features and we need a way of recognizing where the page is being rendered.
1. Access the [workspace](https://vitorflg2--muji.myvtex.com/admin/cms/site-editor)
2. All the blocks should be identified by the block selector
| ✔️ | New feature                        |
X

Add site editor flag in the iframe url

---

CHANGELOG.md
react/components/EditorContainer/Topbar/ContextSelectors/index.tsx

Add query string identifying the site editor when user updates the binding.
https://vitorflg--muji.myvtex.com/admin/cms/site-editor
X
| ✔️ | New feature                        |
X

Add flag when navigating between bindings

---

CHANGELOG.md
react/RedirectForm.tsx
react/components/admin/redirects/Form/index.tsx
react/components/admin/redirects/Form/typings.d.ts
react/components/admin/redirects/Form/utils.ts
react/components/admin/redirects/List/List.tsx
react/components/admin/redirects/List/index.tsx
react/components/admin/redirects/List/messages.tsx
react/package.json
react/queries/DeleteRedirect.graphql
react/queries/Redirect.graphql
react/queries/Redirects.graphql
react/queries/SaveRedirect.graphql
react/typings/global.d.ts
react/yarn.lock

Currently managing redirects in multi-language stores is hard, since it can only be done via APIs. This PR solves that by improving the Redirects UI in the admin to vary by binding.
[Workspace](https://redirectsui--muji.myvtex.com/admin/cms/redirects/)

Adds binding information in Redirects UI

---

CHANGELOG.md
messages/context.json
messages/en.json
messages/es.json
messages/fr.json
messages/it.json
messages/ja.json
messages/ko.json
messages/nl.json
messages/pt.json
messages/ro.json
react/PageEditor.tsx
react/components/TemporaryAlert/index.tsx
react/package.json
react/yarn.lock

Warns customers on the `newadmin` production workspaces, which hosts the Admin's beta version, to navigate back to the master workspace in case they want to edit their stores.
Navigate to this [workspace](https://newadmin--teamadmin.myvtex.com/admin/cms/site-editor) and make sure that you see an alert on top of the Site Editor 😉 
NOTE: Although you'll see the yellow, development banner, this won't be true once this PR is merged, because the linked version doesn't contain the `production` check.
NOTE 2: These changes should only be apparent for customers on the `admin@4.x`, which doesn't have the same amount of languages available as the `admin@3.x`, thus, there are English translations placed on other languages, as the CI will fail in case the `intl-equalizer` doesn't find the same …

NAD-530 - Add temporary newadmin warning

---

CHANGELOG.md
messages/en.json
messages/es.json
messages/fr.json
messages/it.json
messages/ja.json
messages/ko.json
messages/nl.json
messages/pt.json
messages/ro.json

Shorten message from the temporary `newadmin` workspace warning. 
Related thread on Slack: https://vtex.slack.com/archives/C01KE2JBL5P/p1623159536005400
[Workspace](https://marcelo--teamadmin.myvtex.com/admin/cms/site-editor)
NOTE: The workspace above has changes that are not reflected on this PR in order for it to appear since it should only be displayed on `production` workspaces named `newadmin`.
| ✔️   | Technical improvements  |
For more context on this, please reach …

Shorten message from the temporary newadmin workspace warning

---

CHANGELOG.md
react/RedirectList.tsx

The number of redirects displayed on cms/redirects screen is less than it should
Showing 9
Should be 10
1 - Go to any account at admin/cms/redirects
2 - Check the number of redirects in the list, it should display 10, but, it's displaying 9
3 - With the fix, should display 10
[Workspace](https://redirects--storecomponents.myvtex.com/admin/cms/redirects/)
Before
After

fix: quantity of redirects being displayed on list

---

CHANGELOG.md
admin/navigation.json

Currently, the `store` module is not available on `admin@4.x`'s sidebar. This PR includes the `store` module on the sidebar.
Compare both workspaces, the current one without the changes from this PR: https://teamadmin.myvtex.com/admin/cms/store (notice how you'll be able to visit the module, but it is not mapped to the sidebar)
And the one with these changes, where the navigation UX is complete: https://store--teamadmin.myvtex.com/admin/cms/store
| ✔️  | Technical …

NAD-618 - Add store module on `admin@4.x`

---

.vtexignore
CHANGELOG.md
messages/context.json
messages/en.json
react/components/EditorContainer/Sidebar/BlockEditor/BlockConfigurationEditor/Form.tsx
react/components/EditorContainer/Sidebar/BlockEditor/BlockConfigurationEditor/index.tsx
react/components/EditorContainer/Sidebar/BlockEditor/hooks.ts
react/components/EditorContainer/graphql/SaveContent.graphql

Since subcategory pages can't have their own context, it's not possible to differentiate their content.
Example > If in the Site Editor, within a category page(/tshirts), I filter the results using a 'blue' option(/thirts/blue), any changes to this page content(banner/rich-text...) will be reflected in all subcategory pages(tshirts/red, tshirts/v-neck...)
To avoid this unintended result, we will be warning users to reset subcategory content to make it be inherited from its parent category.
1. Go to the [workspace](https://vitorflg--storecomponents.myvtex.com/admin/cms/site-editor/apparel---accessories/clothing/white)
2. Make sure the actions are blocked and a warning is advising the default behavior  …

CMS-590 - Warn users about the behavior of changes on subcategory pages

---

CHANGELOG.md
react/RedirectList.tsx
react/components/admin/redirects/List/List.tsx
react/tsconfig.json

Now with this feature, it will be easier to search on redirects.
Having the opportunity to just type part of the page of redirect and avoiding searching page by page.
This special useful when there are more than 1000 redirects in the site
[Workspace](https://test--felipedev.myvtex.com/admin/cms/redirects/)
| ✔️| New feature                        |

Adding a redirect searcher

---

CHANGELOG.md
react/components/admin/redirects/List/List.tsx
react/utils/date/index.ts

The redirects page was not showing up the end date of temporary redirects 
[Before](https://carolcanelas.myvtex.com/admin/cms/redirects/):
Enter a redirect page on the CMS module and try to look for the end date on the UI
[After](https://carolteste--carolcanelas.myvtex.com/admin/cms/redirects/):
Now you can see the end date on the redirects UI
Zendesk Ticket: #833375

fix: end date not displaying in redirects list

---

CHANGELOG.md
react/components/admin/pages/Form/Form.tsx

The main point regarding this issue is that when users change the path of an existent route, we change the path in the routes.json, but we don't change the route id, and we validate if the route already exists or not by the routeId.
What happened is that we were creating a problem when users try to create a new route with the path that was replaced.
For example:
We create a route called `/foo`
We change the route `/foo` to `/foo2`
Now we can't create a new `/foo`
This issue caused a lot of support tickets requesting to identify and remove the duplicated/problematic route due to this usage.
The purpose here is to deny users to change the path of an existing page to stop the blood, and then, in the future, if it makes sense, we allow the users to change the path again once we deep dive into …

fix: when user changed the path of an existent route it only changed the path but not the routeId

---

react/components/EditorContainer/Sidebar/BlockEditor/hooks.ts
react/components/EditorContainer/Sidebar/BlockEditor/index.tsx
react/components/EditorContainer/Sidebar/BlockEditor/typings.d.ts
react/components/EditorContainer/Sidebar/index.tsx

This PR collects `Edit content block` and `Schedule change` events.
Go to this [Workspace](https://auditdev--plannerdev.myvtex.com/admin) and do _Edit Content_ action, this action will be caught and sent to Redshift where it is going to be disposed like this on its GUI
```
[
{
"date": "2024-06-08 01:02:53+00",
"operation": "copy binding content",
"subject_id": "",
"id": "ef7604f1-849f-46e1-b4b9-e853b69a4c88",
}
]
```
https://github.com/vtex-apps/admin-pages/assets/43558278/7ce44ba9-de8a-4f0f-afdd-96611320907f
| ✔️  | …

[TCM-428] Collect "Edit content block" and "Schedule change" events

---

CHANGELOG.md
admin/navigation.json

Remove CMS products from the sidebar when the user doesn't have access.
[Workspace](https://myllenadev--plannerdev.myvtex.com/admin)
We need to try accessing with a user who doesn't have access to any of the CMS apps.
|  X  | Bug fix                                |

TCM-454: Add LMProduct ID - CMS section

---

CHANGELOG.md
react/components/form/ArrayFieldTemplate/ItemForm.tsx
react/components/form/ArrayFieldTemplate/ItemTransitions.css
react/components/form/ArrayFieldTemplate/styles.css

Overflow when opening modal in admin/cms/pages, not giving a good usability
Reverting the way I did for [this PR](https://github.com/vtex-apps/admin-pages/pull/470) because the way we read json schemas is the same in site-editor and the class is being shared, it caused a visual crash
Click in add favicon and check the modal
[Before](https://master--storecomponents.myvtex.com/admin/cms/store)
[After](https://customheader--storecomponents.myvtex.com/admin/cms/store)
| ✔️  | …

fix: modal layout overflow

---

CHANGELOG.md
messages/bg.json
messages/context.json
messages/de.json
messages/en.json
messages/es.json
messages/fr.json
messages/ko.json
messages/nl.json
messages/pt.json
messages/ro.json
messages/th.json

Currently the messages are saved in admin-pages, so, I'm removing the messages from vtex.store and adding into admin-pages
https://github.com/vtex-apps/store/pull/589

refactor: customHeader messages moved to admin-pages

---

CHANGELOG.md
react/RedirectList.tsx
react/queries/RedirectWithoutBinding.graphql

For a large volume of data, searching for redirects is not feasible. This PR allows searching only for the exact term in the `from` variable. It also removes the infinite refetch data to find existing redirect.
The page starts with 1000 items loaded on the client. For these, the search does not need to be exact.
On the [Redirects management page](https://vuvasdev--cea.myvtex.com/admin/cms/redirects), it is possible to search for a `from` url that is not currently on the client. From this, an exact match search will be performed with GraphQL.
`from` path to replicate the test scenario: `/conjunto-menina-blusa-flores-e-aplique-de-laco-e-short-saia-jeans-com-babados-luluzinha-3396853/p`
Request:
Response: …

Add get redirect with full text

---

CHANGELOG.md
messages/context.json
messages/en.json
messages/pt.json

This PR adds a new flag to control bypass render runtime navigation logic, and using native browser navigation
[Workspace](https://paladinoteste--instoresetupqa.myvtex.com/)
* Load the workspace home
* Navigate to any PDP
* You will notice a navigation progress bar at the top of the screen, indicating that it is using Render Runtime navigation solution
* Enable the new flag "Habilitar navegação nativa do navegador" can be enabled/disabled [here](https://paladinoteste--instoresetupqa.myvtex.com/admin/cms/store)
* Wait a few minutes to avoid cached results, refresh the page, and click in the store logo, in the top left, for instance.
* Navigation progress bar should not be rendered anymore, indicating that we navigated through default browser navigation. …

[SFSOC-95] - Add admin flag to enable default browser navigation
