- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- .travis.yml
- CHANGELOG.md
- README.md
- react/.babelrc
- react/__tests__/ComponentEditor.test.js
- react/components/ComponentEditor.js
- react/components/form/BaseInput.js
- react/package.json
- react/yarn.lock
Add edition of static or dynamic schemas on the pages editor.
This solution makes possible to create static or dynamic component schema.
Access: https://dynamic-schema--storecomponents.myvtex.com/
Create a component schema with a property "repeatProperty", like the following example:
```
export const bannerStructure = {
type: 'object',
title: 'banner',
properties: {
image: {
type: 'string',
title: 'Banner image',
},
page: {
type: 'string',
title: 'Banner link',
},
targetParams: {
type: 'object',
title: 'Banner target params',
properties: {
params: {
type: 'string',
title: 'Params',
},
},
},
},
}
```
The component must decide if will use an `static schema` or a `getSchema` function to generate the schema dinamically.
```
static getSchema = ({numberOfBanners}) => {
const …
```
> Add support for dynamic component schema

- CHANGELOG.md
- manifest.json
- react/components/conditions/ConditionSelector.tsx
> Hide scope template option

- CHANGELOG.md
- manifest.json
- react/components/ComponentEditor.tsx
> Fix cancel bug in edit mode

- CHANGELOG.md
- manifest.json
- react/EditorProvider.tsx
- react/components/conditions/ConditionSelector.tsx
- react/typings/global.d.ts
1. Remove both `template` and `site` scope conditions
2. Exit edit mode after using component selector
> Fix scope selector options

- react/EditorProvider.tsx
- react/components/ComponentEditor.tsx
- react/components/ComponentList.tsx
- react/components/EditorContainer.tsx
- react/components/HighlightOverlay.tsx
- react/typings/global.d.ts
Move extension point highlight functionality out of EditorProvider
> Add Highlight Component

- pages/pages.json
- react/locales/en.json
- react/locales/es.json
- react/locales/pt.json
Create Pages subitems @ admin.
Missing Pages links @ admin.
Workspace: https://alan--lojadaju.myvtex.com/admin/.
> Feature - Admin new links

- CHANGELOG.md
- manifest.json
- react/components/EditorContainer.tsx
> Add padding to iframe-container

- CHANGELOG.md
- manifest.json
- react/components/PageForm.tsx
Update page post-save redirect link.
Outdated link.
Workspace: https://alan--lojadaju.myvtex.com/admin/cms/pages/.
> Update page post-save redirect link

- CHANGELOG.md
- manifest.json
- react/PagesAdmin.tsx
- react/locales/en.json
- react/locales/es.json
- react/locales/pt.json
Add i18n to admin tabs.
Untranslated texts.
Workspace: https://alan--lojadaju.myvtex.com/admin/cms/pages.
> Feature - Admin tabs i18n

- CHANGELOG.md
- manifest.json
- react/components/form/ImageUploader/index.js
- react/package.json
- react/yarn.lock
Replace complete file URL with only its `pathname`.
The image URLs must be relative.
Workspace: https://fiximageuploaderurl--lojadaju.myvtex.com/admin/cms/storefront/.
> Fix - ImageUploader URL

- CHANGELOG.md
- manifest.json
- react/components/PageForm.tsx
- react/locales/en.json
- react/locales/es.json
- react/locales/pt.json
- Fix error dialog on success bug;
- Add loading logic to page saving process;
- Add i18n to `PageForm` buttons;
- Remove unused classes from `PageForm`'s save button;
- Remove some `console.log`s.
False positives.
Workspace: https://fixpagesavingerror--lojadaju.myvtex.com/admin/cms/pages.
> Fix - Page saving error

- CHANGELOG.md
- manifest.json
Make a release.
404 issues on registry.
> Empty release to solve caching issues

- CHANGELOG.md
- manifest.json
- react/EditorProvider.tsx
- react/components/ComponentEditor/index.tsx
- react/typings/global.d.ts
Use flag created on render to conditionally update the render-runtime.
Form UX
https://fixformux--storecomponents.myvtex.com/admin/cms/storefront
> Fix JSON Schema form

- react/components/EditorContainer/Sidebar/ComponentList/index.tsx
- react/components/EditorContainer/Sidebar/ComponentList/utils.test.ts
- react/components/EditorContainer/Sidebar/ComponentList/utils.ts
- react/components/EditorContainer/Sidebar/ComponentSelector.tsx
- react/components/EditorContainer/Sidebar/Content.tsx
Reorder extension points on iframe.
[https://reorderruntimeblocks--storecomponents.myvtex.com/admin/cms/storefront](https://reorderruntimeblocks--storecomponents.myvtex.com/admin/cms/storefront)
> Iframe (client-side) is now reordering

- react/components/ComponentsList/getComponents.test.ts
- react/components/ComponentsList/getComponents.ts
Fix the position of `header` and `footer`.
> Fix header and footer position on components array

- react/components/ComponentsList/SortableList/SortableListItem/index.tsx
- react/components/ComponentsList/SortableList/index.tsx
- react/components/EditorContainer.tsx
Fix list header ("Components") height
> Component header height

- CHANGELOG.md
- manifest.json
- react/components/EditorContainer/Sidebar/ConfigurationList/List/Card.tsx
- react/components/admin/redirects/Form/index.tsx
- react/components/admin/redirects/List/index.tsx
- react/components/form/Toggle.tsx
- react/typings/vtex.styleguide.d.ts
Upgrade styleguide to major 8 so that new components can be used.
> Update styleguide to major 8

- react/PageEditor.tsx
- react/components/EditorContainer/Sidebar/ComponentList/index.tsx
- react/components/EditorContainer/Sidebar/ComponentList/typings.d.ts
- react/components/EditorContainer/Sidebar/ComponentList/utils.ts
- react/components/EditorContainer/Sidebar/ConfigurationList/index.tsx
- react/components/EditorContainer/Sidebar/TemplateEditor/index.tsx
- react/queries/AvailableComponents.graphql
- react/queries/UpdateBlock.graphql
- react/typings/global.d.ts
- react/utils/blocks.ts
- react/utils/blocks/index.ts
- react/utils/blocks/typings.d.ts
- react/utils/components.ts
- Create blocks utils;
- Remove `availableComponents` and adapt functions;
- Add saving functionality to `TemplateEditor`;
- Add check for 'params' before accessing 'path`;
- Fix component reordering.
Workspace: https://featureupdateblock--storecomponents.myvtex.com/admin/cms/storefront.
> Feature - Update block

- CHANGELOG.md
- react/components/EditorContainer/StoreEditor/index.tsx
Set a `min-width` to store sidebar and fix it's size
The sidebar used to get smaller with the page.
> Fix store sidebar size

- react/components/EditorContainer/Sidebar/ComponentEditor/index.tsx
- react/components/EditorContainer/StoreEditor/Styles/StyleEditor/ColorsEditor/ColorGroup.tsx
- react/components/EditorContainer/StoreEditor/Styles/StyleEditor/ColorsEditor/index.tsx
- react/components/EditorContainer/StoreEditor/Styles/StyleList/index.tsx
> Fix overflows. Merge redundant divs.

- react/components/form/Dropdown.tsx
Fix Dropdown options labels.
Wrong Dropdown options labels.
Workspace: https://fixdropdownoptionslabels--storecomponents.myvtexdev.com/admin/cms/storefront.
> Fix Dropdown options labels

- CHANGELOG.md
- manifest.json
- package.json
- pages/blocks.json
Remove conditions builder menu link
Conditions builder is deprecated and the link goes to a missing page.
> Remove conditions builder menu link

- react/components/EditorContainer/Sidebar/ComponentList/SortableList/SortableListItem/Item.tsx
- react/components/EditorContainer/Sidebar/ComponentList/SortableList/SortableListItem/index.tsx
- react/components/EditorContainer/Sidebar/ComponentList/index.tsx
- react/components/EditorContainer/Sidebar/ComponentSelector.tsx
- react/components/EditorContainer/Sidebar/EditorHeader/index.tsx
- react/components/icons/ArrowIcon.tsx
- react/editbar.global.css
> Design issues

- messages/context.json
- react/components/EditorContainer/Sidebar/ConfigurationList/List/index.tsx
- react/components/EditorContainer/Sidebar/ConfigurationList/index.tsx
- react/components/EditorContainer/Sidebar/Content.tsx
- react/components/EditorContainer/Sidebar/utils.test.ts
- react/components/EditorContainer/Sidebar/utils.ts
- react/components/admin/pages/Form/stateHandlers/getChangeOperatorConditionalTemplateState.test.ts
- react/components/admin/pages/Form/stateHandlers/getChangeTemplateConditionalTemplateState.test.ts
- react/components/admin/pages/Form/stateHandlers/getRemoveConditionalTemplateState.test.ts
Sitewide content deletion.
1. [Workspace](https://deletesitewidecontent--storecomponents.myvtex.com/admin/cms/storefront)
2. Try to delete Footer content
> Delete sitewide content

- CHANGELOG.md
- manifest.json
- package.json
> Bump to new pwa-graphql major

- CHANGELOG.md
- manifest.json
- react/components/EditorContainer/Sidebar/FormMetaContext.tsx
- react/components/EditorContainer/Sidebar/ModalContext.tsx
Removes duplicity and makes it pass in the new babel7 builder-hub
> makes it pass the new babel7 builder-hub

- CHANGELOG.md
- manifest.json
- package.json
- react/HighlightOverlay.tsx
Improve `HighlightOverlay` scroll into view.
Better UX.
> Improve scroll into view

- CHANGELOG.md
- manifest.json
- package.json
- react/PageEditor.tsx
- react/components/EditorProvider.tsx
Makes `__provideRuntime` still run.
> Catch editor messages

- CHANGELOG.md
- manifest.json
- react/editbar.global.css
Some stores were breaking on storefront because of these styles.
> Remove global styles (v2.x)

- CHANGELOG.md
- manifest.json
- package.json
- react/components/DomainMessages.ts
Splits the components array into many smaller arrays so we don't exceed the querystring limit
> batches messages query

- CHANGELOG.md
- manifest.json
- react/components/EditorContainer/Sidebar/ComponentList/SortableList/SortableListItem/index.tsx
- react/components/EditorContainer/Sidebar/ComponentList/typings.d.ts
- react/components/EditorContainer/Sidebar/ComponentList/utils.test.ts
- react/components/EditorContainer/Sidebar/ComponentList/utils.ts
- react/components/EditorContainer/Sidebar/utils.test.ts
- react/components/EditorContainer/Sidebar/utils.ts
- react/utils/blocks/index.ts
> Nested components list

- CHANGELOG.md
- manifest.json
- react/components/form/BaseInput.tsx
Add i18n to editor description field
> Add i18n to editor description field

- react/components/EditorContainer/Sidebar/ComponentList/typings.d.ts
- react/components/EditorContainer/Sidebar/ComponentList/utils.ts
- react/components/EditorContainer/Sidebar/typings.d.ts
- react/utils/blocks/index.ts
- react/utils/blocks/typings.d.ts
Refactored the code to improve performance (iterating less through data).
Also generalised logic - we were just hoisting top level `before`, `after` and `around` components, instead of doing it on every level.
The logic to build component tree seems simpler, even though the code to hoist the surrounding components adds a bunch of complexity.
> Hide layout elements tweeks

- CHANGELOG.md
- manifest.json
- react/components/form/Radio.tsx
Add format IO messages to radio button labels
Radio button labels being displayed as messages ids.
Edit the content of a component which uses radio button label (e.g. menu inside header block).
> Add format IO messages to radio button labels

- CHANGELOG.md
- manifest.json
- package.json
- react/components/EditorContainer/Sidebar/ConfigurationList/List/Card/index.tsx
- react/components/EditorContainer/Sidebar/ConfigurationList/index.tsx
- react/utils/components/index.ts
- react/utils/components/typings.d.ts
- Fix i18n mapping issues.
- Remove unused CSS class.
I18n mapping issues.
Workspace: [https://fixi18nmapping--storecomponents.myvtex.com/admin/cms/storefront](https://fixi18nmapping--storecomponents.myvtex.com/admin/cms/storefront).
> Fix - I18n mapping

- CHANGELOG.md
- manifest.json
- messages/pt.json
- package.json
- react/components/EditorProvider.tsx
Remove spread from `newState` and only pass the necessary parameters.
Navigation loading wasn't being cleared.
Fix translation.
> Fix navigation loading

- CHANGELOG.md
- manifest.json
- package.json
- react/components/EditorContainer/Sidebar/ComponentEditor/Form.tsx
- react/components/form/I18nInput.tsx
- react/components/form/RichText.tsx
- react/components/form/TextArea.tsx
- react/utils/components/index.ts
Poor rich text edition UX. **This is a temporary solution, and we'll soon have a proper rich text widget.**
Workspace: https://featurerichtextformat--storecomponents.myvtex.com/admin/cms/storefront.
> Feature: rich text format

- CHANGELOG.md
- manifest.json
- package.json
- react/components/EditorContainer/StoreEditor/Styles/StyleEditor/index.tsx
- react/components/EditorContainer/StoreEditor/Styles/StyleList/index.tsx
Change toast position.
Make the feedback closer to where the user is interacting.
> Change styles Toast feedback to the left.

- CHANGELOG.md
- manifest.json
- messages/pt.json
- package.json
A typo in the page creation form.
> Fix: page form typo

- CHANGELOG.md
- react/HighlightOverlay.tsx
- Auto scroll was providing a really poor UX when trying to select a block from the Store iframe.
[Workspace](https://autoscroll--storecomponents.myvtex.com/admin/cms/storefront)
[ch13230]
> Fix autoscroll when selecting

- CHANGELOG.md
- react/components/EditorContainer/Sidebar/ConfigurationList/index.tsx
- react/package.json
- react/utils/components/index.ts
- react/utils/components/typings.d.ts
- react/yarn.lock
Properly resolve i18n content for `JSONSchema` dependencies and arrays
You could go to any of this workspaces and test if footer and menu are internationalizable
https://jey2--storecomponents.myvtex.com/admin/cms/storefront
https://jey--alssports.myvtex.com/admin/cms/storefront
https://jey--invictastores.myvtex.com/admin/cms/storefront
---|---
_ | Bug fix 
> Use `vtex.ajv` to validate dependencies properties for i8nMapping

- .github/PULL_REQUEST_TEMPLATE.md
None.
No need.
---|---
_ | Bug fix 
✔️ | Technical improvements 
Just a fun section on our PR template 😄
> Add section to PR template.

- CHANGELOG.md
- react/components/EditorContainer/Sidebar/utils.test.ts
- react/components/EditorContainer/Sidebar/utils.ts
- react/components/form/Dropdown.tsx
- react/package.json
- react/yarn.lock
- yarn.lock
Blocks such as `Columns` that are supposed to be hidden are showing in the components list.
[Workspace](https://noneditableblocks--instore.myvtex.com/admin/cms/storefront)
[ch15264]
> Non editable blocks showing

- CHANGELOG.md
- react/components/admin/pages/Form/index.tsx
- react/components/admin/pages/utils.ts
> Fix save user route

- CHANGELOG.md
- react/components/admin/pages/Form/index.tsx
- react/components/admin/pages/utils.ts
Get changes from [https://github.com/vtex-apps/admin-pages/pull/251](https://github.com/vtex-apps/admin-pages/pull/251).
> Send all data when user route. 

- CHANGELOG.md
- react/components/admin/institutional/Form/withContentContext.tsx
The reponse below sent by the messages api is causing a break. We're just making the code more resilient with null values.
https://augusto--noux.mygocommerce.com/admin/cms/content/vtex.store%402.x%3Astore.content%23conheca-a-noux/
| ✔️| Bug fix                                |
> Be more resilient with content translations

- react/components/EditorContainer/Sidebar/Content.tsx
Sometimes we should just read the docs, although I think this section is new...
[How to create expensive objects lazily?
](https://reactjs.org/docs/hooks-faq.html#how-to-create-expensive-objects-lazily)
Multiple calls to `useMemo`
Trust me.
> Fix getInitialComponents

- CHANGELOG.md
- admin/navigation.json
- admin/routes.json
- docs/CONTENT_PAGE.md
- messages/context.json
- messages/en.json
- messages/es.json
- messages/pt.json
- react/PageEditor.tsx
- react/components/EditorContainer/Sidebar/ConfigurationList/index.tsx
- react/components/EditorProvider.tsx
- react/package.json
- react/yarn.lock
- Rename "Storefront" to "Site Editor";
- Add a redirect from pages with `storefront` to `site-editor`;
- Make CI scripts run in parallel.
[Workspace](https://chorerenamestorefront--storecomponents.myvtex.com/admin/cms/site-editor/)
N/A.
> Chore - Rename Storefront

- README.md
Documentation url is incorrect.
> Applied url fix pointed to documentation

- README.md
Symlink was useless [according to github](https://help.github.com/en/articles/about-readmes) (ty @alcar and @saviofelixmuniz for teaching me that <3)
| ✔️| Technical improvements  |
> Remove README.md symlink.

- CHANGELOG.md
- messages/es.json
- messages/pt.json
> Fix locale switcher messages

- messages/context.json
- messages/en.json
- messages/es.json
- messages/pt.json
- react/components/EditorContainer/Sidebar/AbsoluteLoader.tsx
- react/components/EditorContainer/Sidebar/BlockEditor/BlockConfigurationEditor/index.tsx
- react/components/EditorContainer/Sidebar/BlockEditor/BlockConfigurationList/hooks.ts
- react/components/EditorContainer/Sidebar/BlockEditor/BlockConfigurationList/index.tsx
- react/components/EditorContainer/Sidebar/BlockEditor/BlockConfigurationList/typings.d.ts
- react/components/EditorContainer/Sidebar/BlockEditor/EditorHeader.tsx
- react/components/EditorContainer/Sidebar/BlockEditor/hooks.ts
- react/components/EditorContainer/Sidebar/BlockEditor/index.tsx
- react/components/EditorContainer/Sidebar/BlockEditor/typings.d.ts
- react/components/EditorContainer/Sidebar/BlockEditor/utils.ts
- react/components/EditorContainer/Sidebar/BlockSelector/BlockList/index.tsx
- react/components/EditorContainer/Sidebar/BlockSelector/index.tsx
- react/components/EditorContainer/Sidebar/Transitions/Enter/index.tsx
- react/components/EditorContainer/Sidebar/Transitions/Enter/styles.css
- react/components/EditorContainer/Sidebar/Transitions/Exit/index.tsx
- react/components/EditorContainer/Sidebar/Transitions/Exit/styles.css
- react/components/EditorContainer/Sidebar/Transitions/consts.ts
- react/components/EditorContainer/Sidebar/Transitions/index.tsx
- react/components/EditorContainer/Sidebar/Transitions/typings.d.ts
- react/components/EditorContainer/Sidebar/consts.ts
- react/components/EditorContainer/Sidebar/hooks.ts
- react/components/EditorContainer/Sidebar/index.tsx
- react/components/EditorContainer/Sidebar/styles.css
- react/components/EditorContainer/Sidebar/typings.d.ts
- react/components/EditorContainer/Sidebar/utils.ts
- react/components/EditorContainer/index.tsx
Lack of depth perception when navigating through the different stages of editing a block and its configurations.
[Workspace](https://refactor--storecomponents.myvtex.com/admin/app/cms/site-editor)
N/A.
> Sidebar CSS transitions

- CHANGELOG.md
- react/components/admin/institutional/Form/withContentContext.tsx
- react/queries/ContentIOMessage.graphql
This app is currently using a deprecated API from messages. This PR fixes this problem by using the new API
[Workspace](https://gimenes2--storecomponents.myvtex.com/admin)
> Translatable V2

- CHANGELOG.md
- messages/context.json
- messages/en.json
- messages/es.json
- messages/pt.json
- react/components/EditorContainer/Sidebar/BlockEditor/BlockConfigurationList/Card/index.tsx
- react/components/EditorContainer/Sidebar/BlockEditor/BlockConfigurationList/index.tsx
- react/components/EditorContainer/Sidebar/BlockEditor/BlockConfigurationList/utils.ts
- react/typings/global.d.ts
We are reordeinrg the block configuration cards (the ones you see when
clicking to edit a block) to bring more clarity to what configurations
are relevant.
Here is the order we'll be showing the cards:
1- Active card
2- Scheduled cards (set to this page)
3- Inactive cards (set to this page)
4- Scheduled cards* (set to this template)
5- Inactive cards (set to this template)
6- All expiered scheduled cards
The cards set to "this page" trump over the "this template" ones, so for
that reason they are displayed above them.
1- Edit the first "rich text" block in the page
2- Go to the "content list"
3- Check if the order of the cards match the description above
You can try editing things around and see if it behaves as expected.
[Workspace](https://nardi--storecomponents.myvtex.com/admin/app/cms/ …
> Reorganize cards order

- CHANGELOG.md
- react/components/EditorContainer/Sidebar/BlockEditor/BlockConfigurationList/index.tsx
This is a small UI fix. An unwated shadow was appearing in the block list
[Workspace](https://ch25273--storecomponents.myvtex.com/admin/app/cms/site-editor)
| Before      | After     |
| :------------- | :----------: |
|  <img width="243" alt="Screen Shot 2019-11-14 at 16 04 51" src="https://user-images.githubusercontent.com/1354492/68906432-0fcdf280-06f9-11ea-82d7-d506fcb27f3c.png"> | <img width="244" alt="Screen Shot 2019-11-14 at 16 07 36" src="https://user-images.githubusercontent.com/1354492/68906435-12c8e300-06f9-11ea-9c95-2953125e1b42.png">   |
| \_  | Bug fix …
> Fix: card list bottom not taking full height

- CHANGELOG.md
- react/components/EditorContainer/Sidebar/index.tsx
Sidebar width.
[Workspace](https://fixsidebarwidth--storecomponents.myvtex.com/admin/cms/site-editor)
Before:
After:
> Fix sidebar width

- CHANGELOG.md
- react/components/DomainMessages/editorMessagesFromRuntime.ts
- react/components/admin/pages/Form/stateHandlers/getValidateFormState.ts
- react/components/admin/redirects/Form/Operations.tsx
- react/package.json
- react/yarn.lock
Split in more components by page to decrease amount of messages in request, making less probable a timeout
https://vtex.slack.com/archives/C9P4RMW6Q/p1576094202037700
[Workspace](https://gimenes--storecomponents.myvtex.com/admin/cms/site-editor)
> Not translated messages: The return of the intl

- CHANGELOG.md
- react/components/DomainMessages/editorMessagesFromRuntime.ts
Tries to make messages timeouts less frequent.
> try to decrease messages timeouts

- CHANGELOG.md
- react/components/admin/store/PWAForm/index.tsx
The splash screen is taking some time to be loaded.
**Before**
**After**
[Workspace](https://thay2--storecomponents.myvtex.com/admin/cms/store)
Go to advance.
> add splash screen image loading animation

- CHANGELOG.md
- messages/context.json
- messages/en.json
- messages/es.json
- messages/pt.json
- react/PageList.tsx
- react/components/admin/pages/List/index.tsx
- react/components/admin/pages/List/typings.d.ts
As the title says
[Workspace](https://iaronaraujo--storecomponents.myvtex.com/admin/cms/pages)
> Add "Not found (404)" category on pages.

- CHANGELOG.md
- messages/context.json
- messages/en.json
- messages/es.json
- messages/pt.json
- react/RedirectList.tsx
- react/components/admin/redirects/consts.ts
- react/queries/Redirects.graphql
Updates redirects list to use new correct API
https://newredirect--storecomponents.myvtex.com/admin/cms/redirects/
> Updates redirects list

- CHANGELOG.md
> Useless modification to trigger release bots to go

- react/RedirectForm.tsx
> fix form types

- CHANGELOG.md
- react/RedirectList.tsx
- react/components/admin/redirects/consts.ts
- react/queries/Redirects.graphql
- react/typings/global.d.ts
This reverts commit 40e5f736205c46f7cf1ff0499db145d9b436b6bc.
> Revert "add binding field to redirects spreadsheet"

- react/components/admin/pages/Form/utils.ts
> Fixes routes cache on update

- CHANGELOG.md
- admin/navigation.json
Site Editor is the most accessed item on the `Storefront` section, so we decided to put it as the first item on this section.
[Workspace](https://lucasan--storecomponents.myvtex.com/admin/cms/site-editor)
**Before**
**After**
> Change position of the Site Editor on the admin V4 sidebar

- CHANGELOG.md
- react/components/EditorContainer/Sidebar/BlockSelector/index.tsx
A video is worth a thousand words
Before:
https://www.loom.com/share/a854e0cd952541b5890c2cc4a14d8530
After:
https://www.loom.com/share/68372ee0c419441c957a6b5a3c6e8ab2
https://vitorflg--storecomponents.myvtex.com/admin/cms/site-editor
X
X
> Block selector improvement on multi-binding stores

- CHANGELOG.md
- react/components/EditorContainer/Sidebar/index.tsx
A video is worth a thousand words
Before:
https://www.loom.com/share/ca9a4734760d4039bde305d025980d36
After:
https://www.loom.com/share/73fa3029240e483a9c33ffda9f8cbc78
[https://vitorflg--cea.myvtex.com/admin/cms/site-editor
](https://vitorflg--cea.myvtex.com/admin/cms/site-editor
)
X
X
> Fix scroll on the sidebar editor panel

- CHANGELOG.md
- react/components/EditorContainer/Sidebar/index.tsx
- react/components/MediaGalleryWidget/index.tsx
- react/components/form/ImageUploader/ImagePreview.tsx
- react/components/form/ImageUploader/styles.css
- Drag and drop not working when an image is already selected
- Performance improvements to load image previews
[Workspace](https://vitorflg--storecomponents.myvtex.com/admin/cms/site-editor)
> Enhance image uploader widget

- CHANGELOG.md
- react/components/TemporaryAlert/index.tsx
- react/package.json
- react/yarn.lock
Fixed: Toast overflows the bottom-right corner, making the app unresponsive in that section.
Related thread: https://vtex.slack.com/archives/C9BA2V80K/p1626718508172400
[Workspace](https://matheusoncall--cuerosvelezgt.myvtex.com/admin/cms/site-editor)
| ✔  | Bug fix                                |
> Fix admin-ui toast overflow

- CHANGELOG.md
- react/package.json
- react/yarn.lock
Fixed the overflow problem again
[Workspace](https://matheus--cuerosvelezgt.myvtex.com/admin/cms/site-editor)
> Update admin-ui to latest version

- messages/fr.json
- messages/it.json
- messages/ja.json
- messages/ko.json
- messages/nl.json
- messages/ro.json
Fix extra slashes in old translations
> Fix old translations

- CHANGELOG.md
- manifest.json
Motivation: https://vtex.slack.com/archives/CCYP7AS59/p1652969591674689
> Upgrade admin-cms to 1.x as dependency

- CHANGELOG.md
- messages/en.json
Add new messages for previously hardcoded strings rendering in other apps. Tracked by task [LOC-8204](https://vtex-dev.atlassian.net/browse/LOC-8204) and connected to this [PR](https://github.com/vtex/builder-hub/pull/1150).
[thai--localization](https://thai--localization.myvtex.com/admin/cms/store)
> Add new messages

- CHANGELOG.md
- messages/context.json
- messages/th.json
Add new messages to the context.json and Thai messages files to fix previously hardcoded strings rendering in other apps. Tracked by task [LOC-8204](https://vtex-dev.atlassian.net/browse/LOC-8204) and connected to [this PR](https://github.com/vtex/builder-hub/pull/1150).
[thai--localization](https://thai--localization.myvtex.com/admin/cms/store)
|  ✔️ | Bug fix                                |
> Fix TH and context messages

- CHANGELOG.md
- messages/th.json
Missing comma in thai message when rebasing
> fix: rebasing thai message without comma

- CHANGELOG.md
- messages/ar.json
- messages/bg.json
- messages/context.json
- messages/en.json
- messages/es.json
- messages/fr.json
- messages/it.json
- messages/ja.json
- messages/ko.json
- messages/nl.json
- messages/pt.json
- messages/ro.json
- messages/th.json
Fix missing message in Card index.tsx file for all languages. Tracked in task [LOC-9161](https://vtex-dev.atlassian.net/browse/LOC-9161).
> Fix missing messages

- CHANGELOG.md
- messages/bg.json
- messages/context.json
- messages/es.json
- messages/fr.json
- messages/ko.json
- messages/nl.json
- messages/th.json
It relates to the task [LOC-13251](https://vtex-dev.atlassian.net/browse/LOC-13251). It fixes translations for the Robots-related strings.
[LOC-13251]: https://vtex-dev.atlassian.net/browse/LOC-13251?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix translations for Robots

- CHANGELOG.md
- manifest.json
- react/components/ComponentEditor/index.tsx
- react/components/form/ArrayList.tsx
- react/package.json
- react/yarn.lock
`apps-graphql` has a new major that fixes some issues
[Motivation](https://vtex.slack.com/archives/C075D3PMS2Y/p1716839851735999)
[Workspace](https://jardely--content.myvtex.com/admin/cms/storefront)
> Update apps-graphql version

- react/components/EditorContainer/graphql/SendEventToAudit.graphql
- react/components/EditorContainer/mutations/SendEventToAudit.tsx
- react/package.json
- react/yarn.lock
This PR creates `sendEventToAudit` mutation and a function that creates the event to send to audit.
Considering that this PR has only the mutation and its auxiliary function, there is not a way to test it appropriately without running it locally.
| ✔️ | New feature                        |
> [TCM-450] Create mutation on admin-pages to send events to pages-graphql api

- react/components/EditorContainer/Styles/StyleEditor/StyleEditorHooks.tsx
- react/components/EditorContainer/Styles/StyleEditor/index.tsx
- react/components/EditorContainer/Styles/StyleList/index.tsx
- react/utils/auditEvents/index.ts
This PR collects `create new`, `edit`, `delete` and `select as main` style events.
Go to this [Workspace](https://auditdev--plannerdev.myvtex.com/admin) and do some action related to style, this action will be caught and sent to Redshift where it is going to be disposed like this on its GUI
```
[
{
"date": "2024-06-08 01:03:53+00",
"operation": "edit style",
"subject_id": "10f21650b3cd0fd8c479fa69b510e929",
"id": "4161d6d3-6eb4-45f8-bed4-de617c2f678d",
},
{
"date": "2024-06-08 01:03:54+00", …
```
> [TCM-433] Collect events related to Styles

- react/components/EditorContainer/Topbar/ContextSelectors/BindingCloning/BindingCloningModal.tsx
This PR collects `copy binding content` event.
Go to this [Workspace](https://auditdev--plannerdev.myvtex.com/admin) and do _Copy Binding_ action, this action will be caught and sent to Redshift where it is going to be disposed like this on its GUI
```
[
{
"date": "2024-06-08 01:02:53+00",
"operation": "copy binding content",
"subject_id": "",
"id": "ef7604f1-849f-46e1-b4b9-e853b69a4c88",
}
]
```
https://github.com/vtex-apps/admin-pages/assets/43558278/31aff514-d6d6-41ec-a27c-5997e1c096d8 …
> [TCM-431] Collect "Copy binding content" event

- react/components/EditorContainer/Sidebar/BlockEditor/hooks.ts
This PR collects `Activate content block version` event.
Go to this [Workspace](https://auditdev--plannerdev.myvtex.com/admin) and do _Activate Content_ action, this action will be caught and sent to Redshift where it is going to be disposed like this on its GUI
```
[
{
"date": "2024-06-08 01:02:53+00",
"operation": "copy binding content",
"subject_id": "",
"id": "ef7604f1-849f-46e1-b4b9-e853b69a4c88",
}
]
```
https://github.com/vtex-apps/admin-pages/assets/43558278/88535fc5-83a0-4fcc-83d9-40fcaea3bbf0
| ✔️  | Type of …
> [TCM-432] Collect "Activate content block version" event

- react/components/EditorContainer/Sidebar/BlockEditor/BlockConfigurationList/hooks.ts
- react/components/EditorContainer/Sidebar/BlockEditor/BlockConfigurationList/index.tsx
- react/components/EditorContainer/Sidebar/BlockEditor/BlockConfigurationList/typings.d.ts
- react/components/EditorContainer/Sidebar/BlockEditor/index.tsx
This PR collects `Reset content block version` and `Delete content block version` events.
Go to this [Workspace](https://auditdev--plannerdev.myvtex.com/admin) and do _Reset_ or _Delete_ content block version action, this action will be caught and sent to Redshift where it is going to be disposed like this on its GUI
```
[
{
"date": "2024-06-08 01:02:53+00",
"operation": "copy binding content",
"subject_id": "",
"id": "ef7604f1-849f-46e1-b4b9-e853b69a4c88",
}
]
``` …
> [TCM-430] Collect "Delete content block version" and "Reset content block version" events

- CHANGELOG.md
- react/components/admin/redirects/UploadModal/index.tsx
It's described [here](https://vtex-dev.atlassian.net/browse/TCM-511?focusedCommentId=288544&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-288544).
[Workspace](https://redirects--carolcanelas.myvtex.com/admin/cms/redirects/)
> TCM-511: Fix processedRedirects value attribution

- react/components/EditorContainer/graphql/SendEventToAudit.graphql
[Workspace](https://auditdev--plannerdev.myvtex.com/admin)
| ✔️ | Bug fix                                |
> Fix sendEventToAudit mutation input

- CHANGELOG.md
- react/components/form/ArrayFieldTemplate/ItemTransitions.css
Overflow when opening modal in admin/cms/pages, not giving a good usability
Click in add favicon and check the modal
[Beforer](https://master--storecomponents.myvtex.com/admin/cms/store)
[After](https://customheader--storecomponents.myvtex.com/admin/cms/store)
> fix: modal overflow

- CHANGELOG.md
- react/RedirectList.tsx
- react/components/admin/redirects/bulkUploadRedirects.ts
Lack of feedback on import progress. The progress bar does not work properly, jumping from 0 to 100 at the end of the import.
Perform the import of 400+ redirects in the [workspace](https://importredirects--storecomponents.myvtex.com/admin/cms/redirects) where the fix is linked.
> [SFS-1955] Improvements in Redirect Management
